name: Deploy MB source code to S3

#Mnually trigger workflow
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        #Check out repo
      - name: Checkout repository
        uses: actions/checkout@v2
      #Install nodejs version 18.16.0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      # Install dependecies
      - name: Install dependencies
        run: npm ci
      # Run build
      - name: Build
        run: npm run build

      # Upload Artifact
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: static-file
          path: ./dist

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "./build"

    

